"""add sort_order to company_members

Revision ID: 737f741df8a7
Revises: 7d19bd7c379c
Create Date: 2026-08-12 17:43:26.531170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737f741df8a7'
down_revision: Union[str, Sequence[str], None] = '7d19bd7c379c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_members', sa.Column('sort_order', sa.Integer(), server_default='1000', nullable=True))
    op.alter_column('company_members', 'role',
               existing_type=postgresql.ENUM('admin', 'manager', 'worker', name='companyrole'),
               nullable=False)
    op.alter_column('company_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('company_members', 'role',
               existing_type=postgresql.ENUM('admin', 'manager', 'worker', name='companyrole'),
               nullable=True)
    op.drop_column('company_members', 'sort_order')
    # ### end Alembic commands ###
